### ISSUE TITLE
Demo server with Task data

### ISSUE THREAD

**Issue by jeremyklein** [HL7-DaVinci/MRP-Payer-App#2]
I was able to connect this reference implementation with the SMART app launcher however I wasn't able to find any patient that has a Task resource. Can you point me in the direction of a demo server that has the necessary data to demo this implementation?

**Comment by nschwertner** [comment]
In the MRP use case reference implementation, the Provider app generates a payload which includes a Task among the others (see Task template here https://github.com/HL7-DaVinci/MRP-Reference-App/blob/master/js/config.js#L157-L197). The payload is posted to the `$submit` operation endpoint at the payer implementation. In the reference implementation, the `$submit` is implemented at this sandbox: https://sandbox.logicahealth.org/DaVinciMRPPayer In this instance the payload resources are retained by the receiving sandbox, so try searching for Task resources there.

**Comment by nschwertner** [comment]
Please submit any questions and support requests for the MRP RI here: https://chat.fhir.org/#narrow/stream/180806-Da-Vinci.20MRP

**Comment by nschwertner** [comment]
For general DaVinci discussion/support: https://chat.fhir.org/#narrow/stream/179283-Da-Vinci
